### PR TITLE
Implement 'Add 'function

### PR DESCRIPTION
**Pull request by noeyheadb**
implement add function in 'test.c'

plz merge this

### CODE REVIEW

**Comment by dae-hyeon** [comment]
Hmm..............
wait

**Comment by dae-hyeon** [comment]
#2 ???

**Comment by dae-hyeon** [comment]
We want 'substract' function

**Comment by noeyheadb** [comment]
aleardy implemeted

**Comment by dae-hyeon** [comment]
resolve #2

**Pull request merged**
